# Generated by Django 5.1.6 on 2025-08-27 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dvciceMst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dvcName', models.CharField(max_length=30)),
                ('dvcKind', models.CharField(max_length=15, null=True)),
                ('dvcMaker', models.CharField(max_length=30, null=True)),
                ('dvcModel', models.CharField(max_length=30, null=True)),
                ('dvcPurchase', models.DateField(null=True)),
                ('dvcWarranty', models.DateField(null=True)),
                ('dvcUser', models.CharField(max_length=15, null=True)),
                ('dvcPlace', models.CharField(max_length=30, null=True)),
                ('dvcAssetnumber', models.CharField(max_length=30, null=True)),
                ('dvcStatus', models.CharField(max_length=15, null=True)),
                ('dvcSerialnumber', models.CharField(max_length=30, null=True)),
                ('dvcOS', models.CharField(max_length=15, null=True)),
                ('dvcCPU', models.CharField(max_length=15, null=True)),
                ('dvcRAM', models.CharField(max_length=15, null=True)),
                ('dvcGraphic', models.CharField(max_length=15, null=True)),
                ('dvcStorage', models.CharField(max_length=15, null=True)),
                ('dvcIP', models.CharField(max_length=30, null=True)),
                ('dvcNetWork', models.CharField(max_length=30, null=True)),
                ('dvcNotes', models.CharField(max_length=200, null=True)),
                ('dvcDeleteFlag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserMst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usrLoginID', models.CharField(max_length=15)),
                ('usrName', models.CharField(max_length=15)),
                ('usrPassWord', models.CharField(max_length=15)),
                ('usrKind', models.CharField(choices=[('admin', '管理者'), ('customer', '顧客')], max_length=15)),
                ('usrDeleteFlag', models.BooleanField(default=False)),
                ('usrMail', models.CharField(blank=True, max_length=30, null=True)),
                ('usrCustomer', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dvciceSoftMst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dvsSoftName', models.CharField(max_length=30)),
                ('dvsWarranty', models.DateField()),
                ('dvsDeleteFlag', models.BooleanField(default=False)),
                ('dvsDeviceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dvs_dvc_id', to='Device.dvcicemst')),
            ],
        ),
        migrations.AddField(
            model_name='dvcicemst',
            name='dvcCustomer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dvc_usr_id', to='Device.usermst'),
        ),
    ]
