# Generated by Django 5.1.6 on 2025-08-28 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dvciceMst',
            new_name='DeviceMst',
        ),
        migrations.RenameModel(
            old_name='dvciceSoftMst',
            new_name='DeviceSoftMst',
        ),
    ]
