# Generated by Django 5.1.6 on 2025-08-28 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0002_rename_dvcicemst_devicemst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemst',
            name='dvcAssetnumber',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='devicemst',
            name='dvcCPU',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='devicemst',
            name='dvcGraphic',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='devicemst',
            name='dvcIP',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='devicemst',
            name='dvcKind',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='devicemst',
            name='dvcMaker',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='devicemst',
            name='dvcModel',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='devicemst',
            name='dvcNetWork',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='devicemst',
            name='dvcNotes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='devicemst',
            name='dvcOS',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='devicemst',
            name='dvcPlace',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='devicemst',
            name='dvcPurchase',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicemst',
            name='dvcRAM',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='devicemst',
            name='dvcSerialnumber',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='devicemst',
            name='dvcStatus',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='devicemst',
            name='dvcStorage',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='devicemst',
            name='dvcUser',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='devicemst',
            name='dvcWarranty',
            field=models.DateField(blank=True, null=True),
        ),
    ]
