# Generated by Django 5.1.6 on 2025-08-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0003_alter_devicemst_dvcassetnumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermst',
            old_name='usrDeleteFlag',
            new_name='usrDelete',
        ),
        migrations.AlterField(
            model_name='usermst',
            name='usrKind',
            field=models.IntegerField(choices=[('1', '顧客'), ('2', '管理者')]),
        ),
    ]
