# Generated by Django 5.1.6 on 2025-08-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0004_rename_usrdeleteflag_usermst_usrdelete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermst',
            name='usrKind',
            field=models.IntegerField(choices=[('顧客', '1'), ('管理者', '2')]),
        ),
    ]
