# Generated by Django 5.1.6 on 2025-08-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0005_alter_usermst_usrkind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermst',
            name='usrKind',
            field=models.IntegerField(choices=[(1, '顧客'), (2, '管理者')]),
        ),
    ]
