# Generated by Django 5.1.6 on 2025-09-03 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0006_alter_usermst_usrkind'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermst',
            name='customerImage',
            field=models.ImageField(blank=True, null=True, upload_to='customer_images/'),
        ),
    ]
