# Generated by Django 5.1.6 on 2025-09-16 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0007_usermst_customerimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermst',
            name='customerImage',
        ),
        migrations.AddField(
            model_name='usermst',
            name='usrDeviceMap',
            field=models.ImageField(blank=True, null=True, upload_to='device_maps/'),
        ),
    ]
